### ISSUE TITLE
求指点：如何解决AttributeError: 'numpy.bytes_' object has no attribute 'delta'

### ISSUE THREAD

**Issue by YUAN97Q** [zhengchuanpan/GMAN#21]
utils.py中 timeofday = (Time.hour * 3600 + Time.minute * 60 + Time.second) // Time.freq.delta.total_seconds() 这一句报错

Traceback (most recent call last):
  File "/Users/crowd/PycharmProjects/GMAN/METR/train.py", line 55, in <module>
    mean, std) = utils.loadData(args)
  File "/Users/crowd/PycharmProjects/GMAN/METR/utils.py", line 73, in loadData
    timeofday = (Time.hour * 3600 + Time.minute * 60 + Time.second) // Time.freq.delta.total_seconds()
AttributeError: 'numpy.bytes_' object has no attribute 'delta'

我没有修改过作者源码 请问这个问题大家是怎么解决的

**Comment by childe-wuhen** [comment]
请问你解决了吗

**Comment by YUAN97Q** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhengchuanpan/GMAN"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月10日(星期六) 中午11:51
收件人:&nbsp;"zhengchuanpan/GMAN"<GMAN@noreply.github.com&gt;;
抄送:&nbsp;"九亿少女梦――"<2569627904@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhengchuanpan/GMAN] 求指点：如何解决AttributeError: 'numpy.bytes_' object has no attribute 'delta' (#21)





 
请问你解决了吗

**Comment by TBS1234** [comment]
请问您解决了吗，我也是同样的问题

**Comment by flowingrain** [comment]
分母换成3600*24

**Comment by stanli124** [comment]
Time.freq.delta.total_seconds()这个换成 数字 300

**Comment by BeverlyZ** [comment]
> Time.freq.delta.total_seconds()这个换成 数字 300

请问为什么是300呀？

**Comment by 0shelter0** [comment]
> > Time.freq.delta.total_seconds()这个换成 数字 300
> 
> 请问为什么是300呀？
that is because the time slot is 5 mins, i.e. 300 seconds. At corresponding code dividing 300 in order to get the time of day one-hot comes naturally.

**Comment by muratbayrktr** [comment]
In the code change `Time.freq.delta.total_seconds() ` with `args.time_slot*60`.

In the arguments the time_slot is defined in minutes. That's why we are multiplying with 60. I think a more general solution would be to infer the time frequency directly from the h5 df but currently it doesn't seem possible. I couldn't think of more general solution.
